cadena = input('Introduce una palabra: ')
numero = int(input('Introduce un número: '))
decimal = float(input('Introduce un número decimal: '))
print(cadena)
print(type(cadena))
print(numero)
print(type(numero))
print(decimal)
print(type(decimal))